### ISSUE TITLE
Stateless reset

### ISSUE THREAD

**Issue by LPardue** [quicwg/quic-bit-grease#13]
Would it be correct to say that [stateless reset](https://www.rfc-editor.org/rfc/rfc9000.html#section-10.3) packets will never be affected by this extension?

**Comment by martinthomson** [comment]
Good question.

An Initial with a token from (NEW_TOKEN from) a previous connection can clear the bit if the server originally included the transport parameter.  If the server puts this information in the token, processes that token, and decides to send a Retry anyway, it might know that the client previously supported the extension.

The question is whether we want to allow that.  Allowing that means that the client is now constrained (as the server is) to not offer a token if it changes its attitude toward the extension in the interim.  Disallowing it means that Retry doesn't get the benefit of greasing.

The other way this might happen is if the Retry is sent after processing the contents of the Initial packet.  That's much less likely given the way Retry works, but it is at least theoretically possible.

I'm leaning toward forbidding the server from exercising the extension unless it reads the client's opinion from the message it receives.  We don't add a bunch of constraints on how clients offer tokens or tickets elsewhere in the stack and it would be bad form to start.

**Comment by martinthomson** [comment]
Gah, I misread that as Retry.  I keep doing that.

As for stateless reset, it seems unlikely that a server would be able to generate a truly stateless reset with the QUIC Bit cleared.  Except...

A server could condition its use of the QUIC Bit extension on support from the client.  That is, it only declares support for the extension if the client does the same.  In that case, packets it receives with the QUIC Bit cleared would indicate that the client also supports the extension.  In that case, the server would be able to clear the QUIC Bit on its own stateless reset packets.

Aside from that, it seems like it would be hard to be confident that the cleared bit would be acceptable to a client.

**Comment by LPardue** [comment]
Right, we might expect that a QUIC server that has a good relationship with e.g. a Load Balancer might be able to share some information about itself and behaviours. But that sounds too hard for the minimal gain it would provide here, so  I'm pessimistic anyone would bother just for QUIC bit grease.

The new text cuts a good balance on speaking to the consideration and allow people to do what they like.
