### ISSUE TITLE
reasoning behing 7 day rule

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/quic-bit-grease#20]
https://github.com/quicwg/quic-bit-grease/blob/69e1c0689c3f5acb5bc80d4c980794e8cc7f8319/draft-ietf-quic-bit-grease.md?plain=1#L103

Has there been any analysis done for the 7 day rule? or is this just an agreed value. It would be nice to provide some reasoning behind the 7 day rule.

**Comment by martinthomson** [comment]
This matches the recommendations in TLS for session tickets, which prohibit the use of tickets after 7 days.  But I don't think we should hide from the fact that this is completely and unapologetically arbitrary.  Arbitrary is OK; justification only papers over that.

**Comment by zaheduzzaman** [comment]
If this is completely arbitrary then we should not need to recommend this, this is not an experimental specification. In that case it makes sense to even drop it. But I see this is not really that much arbitrary, and reflects the practice for TLS session token. I think we can just say that. in this case we can go from SHOULD to MAY, making it optional. 

by the way I also think, the security consideration falls short on this topic. If we are recommending something then we it is better to say what happens when it is not followed.

**Comment by martinthomson** [comment]
It is arbitrary, but it does need a specified maximum.

What happens when it is not followed is that packets can't be processed.

**Comment by zaheduzzaman** [comment]
yes, if we say something then it will be best to specify a maximum. so the question now from my side is - do we need a strong recommendation (SHOULD) or can we make is optional (MAY)? if we don't have enough experience of actual deployment of it them perhaps it is best that we make it optional. But I am interested to hear why this should be a "SHOULD".

when you say "packets can't be processed" do you mean at server? can we write this down?

**Comment by martinthomson** [comment]
The text already says why:

>  **To allow for changes in server configuration**, clients SHOULD set the QUIC Bit if the token was provided more than 7 days prior.
