### ISSUE TITLE
Cite 7983bis instead of 7983?

### ISSUE THREAD

**Issue by LPardue** [quicwg/quic-bit-grease#23]
AVT core is working on an update that mentions QUIC explicitly, so perhaps we want to ref that?

https://datatracker.ietf.org/doc/draft-ietf-avtcore-rfc7983bis/

**Comment by martinthomson** [comment]
Leaving this one open on the basis that we don't know where 7983bis is at.  Easy to fix in the next revision (and I expect that the status of that doc will be clearer then).
