### ISSUE TITLE
Greasing coalesced packets

### ISSUE THREAD

**Issue by IvanNardi** [quicwg/quic-bit-grease#5]
Hi
I have a doubt about greasing coalesced packets.
Does this grease logic apply only to the first QUIC packet of the UDP datagram or to all the QUIC packets in the same UDP datagram?
In other words, is "0x00" a valid first byte for a coalesced short-header packet?

**Comment by martinthomson** [comment]
The greasing can be applied to all packets independently.  So 0x00 is a valid first byte.

The way to detect padding is to fail to decrypt.  Note also that though many stacks use all zero padding, they aren't required to.

**Comment by IvanNardi** [comment]
Thank you very much for the confirmation and for the suggestion.
Very appreciated.
